### ISSUE TITLE
Broken releases at packagist.org

### ISSUE THREAD

**Issue by Cyberrebell** [zetacomponents/Graph#24]
At [packagist.org - zetacomponents/graph](https://packagist.org/packages/zetacomponents/graph) there is only the dev-master package available but not any more concrete version like 1.5.3 etc.

Can you please restore these broken packagist releases or are there any reasons why you removed them?

**Comment by Hanibal4nothing** [comment]
+1

**Comment by derickr** [comment]
Hey @Cyberrebell - was zetacomponents/Graph available as non ``dev-master`` versions in the past? We certainly didn't remove any concrete versions.

**Comment by Cyberrebell** [comment]
There were release versions in the past as you can see [here](https://web.archive.org/web/20140819220347/https://packagist.org/packages/zetacomponents/graph). It would be nice to have at least the latest release available from packagist.

**Comment by derickr** [comment]
Hey @seldaek and @naderman - any clue what could have happened here?

**Comment by Seldaek** [comment]
Glitch in github api that caused us to clean up some versions as they were not seen in github anymore.. They are restored now, if any other package is affected let me know.

**Comment by Cyberrebell** [comment]
thank you

**Comment by derickr** [comment]
Okay then. Closing this issue.
